management:
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: mars-lottery-server
  profiles:
    active: '@profiles.active@'
  servlet:
    multipart:
      location: /data/service/tmp/mars-lottery
      max-file-size: 100MB
      max-request-size: 1000MB
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    settings:
      number_format: 0.##
      template_update_delay: 0
      template_exception_handler: cn.marsLottery.server.web.FreemakerExceptionHandler

mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml,edusoho/mybatis/*.xml
